### ISSUE TITLE
Don't assume a *NIX system

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/adobe_analytics_api_2.0#3]
In your code, you're silently assume a *NIX system (macOS or GNU/Linux).
For example https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/04e29001025a6440e972efe6b1b9f292aac956a8/adobe_analytics_2/aanalytics2.py#L42 could break on a windows machine.
Join paths using [`os.path.join`](https://docs.python.org/3.8/library/os.path.html#os.path.join) instead.

**Comment by pitchmuc** [comment]
Thanks again. 
I have seen that it causes some issue, especially for the Certificate retrieval. 
When I try to read the path that users are providing for their certificate, it breaks on windows. 
 ` line77  with open(_pathToKey, 'r') as f:`

I prefer to use pathlib than os.path but I need to find a way to decrypt the path before fetching it

**Comment by Ryuno-Ki** [comment]
Could you provide an example of a path before and after decryption?
Perhaps I can provide some tips.

**Comment by pitchmuc** [comment]
I think I found a way to deal with opening the file on different OS. 
The problem is that, I ask for the path to their file, what I did before was trying to open the file directly and people may enter NIX path for window system. So it created problems. 
Now I pass it to the Path class from the pathlib library. 

It seems to automatically detect the path and find. 
I tried with a NIX path on my window machine and it was able to detect the file.

I use it on 2 locations : 
**importConfigFile function** 
```python
#file is the string argument of the function that can be a path or the name of the file.
if file.startswith('/'):
        file = "."+file
    with open(Path(file), 'r') as file:
```

**retrieveToken function** 
```python
# _pathToKey is the string that contains the path.
if _pathToKey.startswith('/'):
        _pathToKey = "."+_pathToKey
    with open(Path(_pathToKey), 'r') as f:
```

What I do, I see if the string start with a slash and assume that if this is case, the user wanted to use a relative path. 
Wondering if I should encapsulate that into a try except function now.

**Comment by pitchmuc** [comment]
I didn't know about this os.sep, I will try to use it in the print output so it match user expectation ! 
Thanks

**Comment by pitchmuc** [comment]
I have updated the code now to reflect the user machine : 
This 
```python
print(' file created at this location : ' + _cwd + '/config_admin.json') 
```
becomes 
```python
print(f" file created at this location : {os.getcwd()}{os.sep}config_admin.json")
```
