### ISSUE TITLE
Issue in Adobe request

### ISSUE THREAD

**Issue by meetu30** [pitchmuc/adobe_analytics_api_2.0#50]
Hi, 
I am trying to capture data from Adobe Analytics API call in Python, but every time I get this error -

error_code: "429050",     "message": "Too many requests"
I am using 2 dimensions and it gets stuck randomly at any point. Although the request limit is 120/minute, I got final record count of 40, sometimes 90, sometimes 3080 and at the end it says "too many requests" 
Could you please provide some input?
Thanks in advance.
Regards,
Meetu

**Comment by pitchmuc** [comment]
Hello @meetu30,
Unfortunately there are very few things to do. 

Are you using aanalytics2 ? 
Which version of the module are you using ? 
You can check that with : `aanalytics2.__version__`
Try to update to the newest version because I should catch these requests normally in my module and account for that. 

If you are trying to re-built a python module for your own use, then you need to add a time.sleep between each call to ensure that it doesn't get above 12 for 6 seconds.

Also, note that the limitation is for everyone using the API, so if you share the API usage with other teams, they may "eat" your limitation.

**Comment by meetu30** [comment]
Hi Pitchmuc,
I am doing this in Python via API call - 
 endpoint = 'https://analytics.adobe.io/api/' + globalCompanyID + '/reports'
Before calling this link, I provide credentials in "header" section and the metrics and dimensions in the "body" section. Once these 2 are set, I call API one by one for individual id. Total Ids that I have stored in list are close to 1000 most of the time. So this API is called at least 1000 times, with the purpose to return me the related metrics and dimension. The issue is that it gets stuck randomly after N number of calls, where N can be 40 /90/400 or any number. I tried to put time.sleep(2) statement right after the above API call, but still the same issue. 
Sometimes I get "too many requests" error displayed on console. 
Sometimes, there is just no error on console, but in log file I see this error - "Error occured: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))" 
Your input is highly appreciated. TIA.

**Comment by pitchmuc** [comment]
Unfortunately, this is the issue of the Adobe API 2.0. 
I would recommend you to raise a ticket on the official Adobe repo or via customer care for that

[repo](https://github.com/AdobeDocs/analytics-2.0-apis)

You "just" need to account for that and setup a "retry" function, I believe I do have one so you can also use the `aanalytics2` module directly ;)

**Comment by meetu30** [comment]
Thanks much Pitchmuc!
